-- Migration 110: Workspace Context & Onboarding Dedup Calibration
-- Created: 2026-06-11

-- ============================================================================
-- WORKSPACE CONTEXT TABLE
-- ============================================================================
-- Stores AI-generated workspace context for assistant personalization

CREATE TABLE IF NOT EXISTS workspace_context (
  org_id TEXT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
  raw_facts JSONB NOT NULL DEFAULT '{}'::jsonb,
  interpreted_context TEXT,
  context_hash TEXT,
  built_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  built_by TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_workspace_context_org_id ON workspace_context(org_id);
CREATE INDEX IF NOT EXISTS idx_workspace_context_built_at ON workspace_context(built_at DESC);

-- RLS: Org isolation
ALTER TABLE workspace_context ENABLE ROW LEVEL SECURITY;

CREATE POLICY workspace_context_org_isolation ON workspace_context
  FOR ALL
  USING (org_id = (auth.jwt() ->> 'org_id'))
  WITH CHECK (org_id = (auth.jwt() ->> 'org_id'));

-- ============================================================================
-- ONBOARDING PROGRESS TABLE UPDATES
-- ============================================================================
-- Add columns for dedup calibration tracking

ALTER TABLE onboarding_progress
  ADD COLUMN IF NOT EXISTS dedup_sample_pairs JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS dedup_calibration_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS dedup_calibration_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dedup_calibration_skipped_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dedup_calibration_result JSONB;

-- Index for onboarding queries
CREATE INDEX IF NOT EXISTS idx_onboarding_progress_dedup_calibration
  ON onboarding_progress(org_id, dedup_calibration_completed);

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE workspace_context IS
  'AI-generated workspace context for personalizing assistant responses. Built by Sonnet 4.6 from raw facts.';

COMMENT ON COLUMN workspace_context.raw_facts IS
  'Structured data from database: connections, harmonies, dedup config, etc.';

COMMENT ON COLUMN workspace_context.interpreted_context IS
  'Natural language summary generated by Sonnet 4.6';

COMMENT ON COLUMN workspace_context.context_hash IS
  'SHA-256 hash of raw_facts for delta detection';

COMMENT ON COLUMN onboarding_progress.dedup_sample_pairs IS
  'JSONB array of sample duplicate pairs (READ-ONLY snapshots, never create cluster records)';

COMMENT ON COLUMN onboarding_progress.dedup_calibration_result IS
  'Suggested survivorship rules and calibration stats';
