#!/usr/bin/env tsx
/**
 * Generate Harmony Bundle
 *
 * This script reads all YAML files from lib/harmonies/library/*.yaml
 * and generates a TypeScript file with inlined YAML content as strings.
 * This ensures the YAML files are bundled at build time instead of
 * relying on filesystem access in production (which fails on Vercel).
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { globSync } from 'glob';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const projectRoot = join(__dirname, '..');
const libraryDir = join(projectRoot, 'lib/harmonies/library');
const outputFile = join(libraryDir, 'generated-bundle.ts');

// Find all YAML files
const yamlFiles = globSync('*.yaml', { cwd: libraryDir }).sort();

if (yamlFiles.length === 0) {
  console.error('No YAML files found in', libraryDir);
  process.exit(1);
}

console.log(`Found ${yamlFiles.length} YAML files`);

// Read and escape YAML content for embedding in TypeScript
const entries: string[] = [];

yamlFiles.forEach((filename) => {
  const filepath = join(libraryDir, filename);
  const content = readFileSync(filepath, 'utf-8');

  // Escape backticks and ${} in the YAML content
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  entries.push(`  '${filename}': \`${escaped}\`,`);
});

const content = `/**
 * Auto-generated bundle of all Harmony YAML files.
 *
 * DO NOT EDIT - This file is generated by scripts/generate-harmony-bundle.ts
 * Run: npm run generate:harmonies
 *
 * Generated at: ${new Date().toISOString()}
 * Files bundled: ${yamlFiles.length}
 */

/**
 * Map of YAML filename to raw YAML content.
 *
 * This ensures all YAML files are bundled at build time and available
 * in serverless environments where filesystem access is restricted.
 */
export const HARMONY_YAML_BUNDLE: Record<string, string> = {
${entries.join('\n')}
};

/**
 * List of all bundled YAML filenames.
 */
export const HARMONY_YAML_FILES: string[] = [
${yamlFiles.map((f) => `  '${f}',`).join('\n')}
];
`;

writeFileSync(outputFile, content, 'utf-8');

console.log(`✓ Generated ${outputFile}`);
console.log(`  Bundled ${yamlFiles.length} files:`, yamlFiles.join(', '));
