/**
 * Provider Adapter Types
 *
 * Common interfaces for all enrichment provider adapters.
 */

// ─────────────────────────────────────────────────────────────
// Core Response Types
// ─────────────────────────────────────────────────────────────

/**
 * Standard response from any provider enrichment call.
 * Includes metadata about the source and when data was retrieved.
 */
export interface ProviderResponse {
  /** Provider ID (e.g., "apollo", "zoominfo") */
  _source: string;
  /** ISO timestamp when data was retrieved */
  _retrieved_at: string;
  /** Raw provider response data */
  raw: Record<string, unknown>;
  /** Optional pre-normalized fields for common use cases */
  normalized?: Record<string, unknown>;
}

/**
 * Contact information from provider search results.
 */
export interface ContactResponse {
  /** Provider ID */
  _source: string;
  /** ISO timestamp when data was retrieved */
  _retrieved_at: string;
  /** Contact details */
  name: string;
  title?: string;
  email?: string;
  phone?: string;
  linkedin_url?: string;
  city?: string;
  state?: string;
  /** Raw provider data */
  raw: Record<string, unknown>;
}

// ─────────────────────────────────────────────────────────────
// Query Types
// ─────────────────────────────────────────────────────────────

/**
 * Query for company enrichment.
 */
export interface CompanyQuery {
  /** Company domain (e.g., "notion.com") */
  domain?: string;
  /** Company name (fallback if domain not provided) */
  name?: string;
}

/**
 * Query for business/company search.
 */
export interface SearchQuery {
  /** Search term or industry type */
  term?: string;
  /** Location filter (city, state, zip) */
  location?: string;
  /** Industry filter */
  industry?: string;
  /** Free text query */
  query?: string;
  /** Max results to return */
  limit?: number;
  /** Capabilities to search for (GraphIQ) */
  capabilities?: string[];
  /** Yelp category filter */
  categories?: string;
}

/**
 * Query for contact search.
 */
export interface ContactQuery {
  /** Company domain to search within */
  domain: string;
  /** Job titles to filter by */
  titles?: string[];
  /** Max contacts to return */
  limit?: number;
}

// ─────────────────────────────────────────────────────────────
// Provider Adapter Interface
// ─────────────────────────────────────────────────────────────

/**
 * Standard interface for all provider adapters.
 * Each provider must implement enrichCompany at minimum.
 */
export interface ProviderAdapter {
  /** Unique provider identifier */
  id: string;
  /** Human-readable provider name */
  name: string;

  /**
   * Enrich a company by domain or name.
   * Returns null if company not found.
   */
  enrichCompany(query: CompanyQuery): Promise<ProviderResponse | null>;

  /**
   * Search for companies/businesses.
   * Optional - not all providers support search.
   */
  search?(query: SearchQuery): Promise<ProviderResponse[]>;

  /**
   * Search for contacts at a company.
   * Optional - not all providers support contact search.
   */
  searchContacts?(query: ContactQuery): Promise<ContactResponse[]>;

  /**
   * Test provider connection and return rate limit headers.
   * Used for rate limit detection when credentials are connected.
   * Optional - not all providers support connection testing.
   */
  testConnection?(): Promise<{
    success: boolean;
    headers?: Headers;
    error?: string;
  }>;
}

// ─────────────────────────────────────────────────────────────
// Error Types
// ─────────────────────────────────────────────────────────────

/**
 * Custom error for provider-specific failures.
 */
export class ProviderError extends Error {
  constructor(
    public provider: string,
    public code: 'auth_error' | 'rate_limit' | 'not_found' | 'api_error' | 'config_error',
    message: string,
    public statusCode?: number
  ) {
    super(`[${provider}] ${message}`);
    this.name = 'ProviderError';
  }
}

// ─────────────────────────────────────────────────────────────
// Utility Types
// ─────────────────────────────────────────────────────────────

/**
 * Brief generated by Clay's Claygent AI.
 */
export interface ClaygentBrief {
  status: 'complete' | 'triggered' | 'pending';
  company_name: string;
  domain?: string;
  brief?: {
    summary: string;
    recent_news?: string[];
    competitive_positioning?: string;
    potential_pain_points?: string[];
    recommended_approach?: string;
  };
  note?: string;
}

/**
 * Business result from local search providers (Serper, Yelp).
 */
export interface LocalBusinessResult {
  name: string;
  address: string;
  phone?: string;
  website?: string;
  rating?: number;
  reviews?: number;
  category?: string;
  hours?: string;
  is_closed?: boolean;
  photos?: string[];
  coordinates?: {
    latitude: number;
    longitude: number;
  };
}

// ─────────────────────────────────────────────────────────────
// Utility Functions
// ─────────────────────────────────────────────────────────────

/**
 * Create a standardized provider response with metadata.
 */
export function createProviderResponse(
  source: string,
  raw: Record<string, unknown>,
  normalized?: Record<string, unknown>
): ProviderResponse {
  return {
    _source: source,
    _retrieved_at: new Date().toISOString(),
    raw,
    normalized,
  };
}

/**
 * Create a standardized contact response.
 */
export function createContactResponse(
  source: string,
  contact: Omit<ContactResponse, '_source' | '_retrieved_at'>
): ContactResponse {
  return {
    _source: source,
    _retrieved_at: new Date().toISOString(),
    ...contact,
  };
}

/**
 * Format revenue number as human-readable string.
 */
export function formatRevenue(revenue: number | string | null | undefined): string {
  if (revenue === null || revenue === undefined) {
    return 'Unknown';
  }

  let numRevenue: number;
  if (typeof revenue === 'string') {
    numRevenue = parseFloat(revenue);
    if (isNaN(numRevenue)) {
      return revenue;
    }
  } else {
    numRevenue = revenue;
  }

  if (numRevenue >= 1_000_000_000) {
    return `$${(numRevenue / 1_000_000_000).toFixed(1)}B`;
  }
  if (numRevenue >= 1_000_000) {
    return `$${Math.round(numRevenue / 1_000_000)}M`;
  }
  if (numRevenue >= 1_000) {
    return `$${Math.round(numRevenue / 1_000)}K`;
  }
  return `$${Math.round(numRevenue)}`;
}
